### PR TITLE
Bump speech-dispatcher dep to 0.13.0

### PR DESCRIPTION
**Pull request by sthibaul**
To avoid typing issues with libspeechd 0.11.0, see
https://gitlab.com/ndarilek/speech-dispatcher-rs/-/issues/3

### CODE REVIEW

**Comment by sthibaul** [comment]
Hello,

I couldn't build this on Debian bullseye:

```
error[E0308]: mismatched types
  --> /home/samy/.cargo/registry/src/github.com-1ecc6299db9ec823/speech-dispatcher-0.11.0/src/lib.rs:35:13
   |
35 |     Male1 = SPDVoiceType::SPD_MALE1,
   |             ^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`
```

and similar for MALE2, MALE3, etc.

This seems to be coming from https://gitlab.com/ndarilek/speech-dispatcher-rs/-/issues/3 , which suggests bumping the speech-dispatcher dependency to 0.13.0, thus this change.

Samuel

**Comment by RastislavKish** [comment]
@sthibaul thanks for reminding me of this!
I set the speech-dispatcher version to 0.11.0 at the time of development, because I had some issues with building the latest version back on Ubuntu Mate 20.04.
However, after an upgrade to 22.04, it works as expected, while the older versions don't (as you mention).
So it seems to be the right time for bumping this.
Could you update the PR with the latest version, 0.13.1 (unless there are problems with it)? I'll merge it then.
Thanks again!

**Comment by sthibaul** [comment]
> Could you update the PR with the latest version, 0.13.1

Does it really have to be the latest version? AIUI one just needs to specify the minimum version requirement.
